[package]
name = "rfq-maker"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
arc-swap = "1"
async-trait.workspace = true
rfq-btc = { path = "../rfq-btc" }
rfq-rgb = { path = "../rfq-rgb" }
rfq-router = { path = "../rfq-router" }
rfq-store = { path = "../rfq-store" }
rfq-types = { path = "../rfq-types" }
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
