[package]
name = "taker-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "colorex-taker"
path = "src/main.rs"

[dependencies]
rfq-types = { path = "../../crates/rfq-types" }
rfq-rgb = { path = "../../crates/rfq-rgb" }
rfq-client = { path = "../../crates/rfq-client" }
rfq-wallet = { path = "../../crates/rfq-wallet" }
dialoguer = { version = "0.11", default-features = false, features = ["password"] }
tokio.workspace = true
clap = { workspace = true, features = ["derive"] }
serde.workspace = true
toml = "0.8"
