[package]
name = "maker-node"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum.workspace = true
clap.workspace = true
rfq-client = { path = "../rfq-client" }
rfq-maker = { path = "../rfq-maker" }
rfq-rgb = { path = "../rfq-rgb" }
rfq-router = { path = "../rfq-router" }
rfq-store = { path = "../rfq-store" }
rfq-types = { path = "../rfq-types" }
rfq-wallet = { path = "../rfq-wallet" }
tokio.workspace = true

[dev-dependencies]
serde.workspace = true
serde_json.workspace = true
tower.workspace = true
