//! Node-identity keypair handling. Generated by `colorex maker init`,
//! persisted to `~/.config/colorex/node.key` (raw 32-byte secret, mode
//! 0600 on Unix) + `~/.config/colorex/node.pub` (hex pubkey sidecar,
//! mode 0644). `node_id` is the first 4 hex chars of the compressed
//! secp256k1 pubkey, prefixed with `node·` — e.g. `node·7af2`.

use std::path::Path;

use secp256k1::{PublicKey, Secp256k1, SecretKey};

#[derive(Debug)]
pub struct NodeKey {
    pub secret: SecretKey,
    pub pubkey: PublicKey,
}

#[derive(Debug)]
pub enum NodeKeyError {
    Io(std::io::Error),
    Secp(secp256k1::Error),
    InvalidLength { expected: usize, actual: usize },
}

impl std::fmt::Display for NodeKeyError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            NodeKeyError::Io(e) => write!(f, "node key io: {e}"),
            NodeKeyError::Secp(e) => write!(f, "node key crypto: {e}"),
            NodeKeyError::InvalidLength { expected, actual } => {
                write!(f, "node key file has {actual} bytes, expected {expected}")
            }
        }
    }
}

impl std::error::Error for NodeKeyError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            NodeKeyError::Io(e) => Some(e),
            NodeKeyError::Secp(e) => Some(e),
            NodeKeyError::InvalidLength { .. } => None,
        }
    }
}

impl From<std::io::Error> for NodeKeyError {
    fn from(e: std::io::Error) -> Self {
        NodeKeyError::Io(e)
    }
}

impl From<secp256k1::Error> for NodeKeyError {
    fn from(e: secp256k1::Error) -> Self {
        NodeKeyError::Secp(e)
    }
}

impl NodeKey {
    /// Generate a fresh secp256k1 keypair from OS randomness.
    pub fn generate() -> Self {
        let secp = Secp256k1::new();
        let (secret, pubkey) = secp.generate_keypair(&mut rand::thread_rng());
        NodeKey { secret, pubkey }
    }

    /// Load a keypair from a raw-bytes secret file (the same format
    /// [`NodeKey::persist`] writes).
    pub fn load(secret_path: &Path) -> Result<Self, NodeKeyError> {
        let bytes = std::fs::read(secret_path)?;
        if bytes.len() != 32 {
            return Err(NodeKeyError::InvalidLength {
                expected: 32,
                actual: bytes.len(),
            });
        }
        let mut buf = [0u8; 32];
        buf.copy_from_slice(&bytes);
        let secret = SecretKey::from_byte_array(&buf)?;
        let secp = Secp256k1::new();
        let pubkey = PublicKey::from_secret_key(&secp, &secret);
        Ok(NodeKey { secret, pubkey })
    }

    /// Atomically write the secret (raw 32 bytes, 0600 on Unix) + the
    /// hex pubkey sidecar (0644). The atomic-rename pattern guards
    /// against half-written keys if the process is interrupted.
    pub fn persist(&self, secret_path: &Path, pubkey_path: &Path) -> Result<(), NodeKeyError> {
        if let Some(parent) = secret_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        atomic_write(secret_path, &self.secret.secret_bytes(), 0o600)?;

        if let Some(parent) = pubkey_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        let pubkey_hex = hex::encode(self.pubkey.serialize());
        atomic_write(pubkey_path, pubkey_hex.as_bytes(), 0o644)?;
        Ok(())
    }

    /// Short human-readable id: `node·<first-4-hex-chars-of-compressed-pubkey>`.
    pub fn node_id(&self) -> String {
        let hex_pub = hex::encode(self.pubkey.serialize());
        format!("node·{}", &hex_pub[..4])
    }
}

fn atomic_write(path: &Path, bytes: &[u8], _mode: u32) -> Result<(), NodeKeyError> {
    let tmp = path.with_extension("tmp");
    std::fs::write(&tmp, bytes)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = std::fs::metadata(&tmp)?.permissions();
        perms.set_mode(_mode);
        std::fs::set_permissions(&tmp, perms)?;
    }
    std::fs::rename(&tmp, path)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn node_id_format_matches_screenshot_shape() {
        let key = NodeKey::generate();
        let id = key.node_id();
        assert!(id.starts_with("node·"), "got {id:?}");
        let suffix = id.strip_prefix("node·").unwrap();
        assert_eq!(suffix.len(), 4, "node_id suffix must be 4 hex chars");
        assert!(
            suffix.chars().all(|c| c.is_ascii_hexdigit()),
            "node_id suffix must be hex: {suffix:?}"
        );
    }

    #[test]
    fn persist_then_load_round_trips() {
        let dir =
            std::env::temp_dir().join(format!("colorex-node-key-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let secret_path = dir.join("node.key");
        let pubkey_path = dir.join("node.pub");

        let original = NodeKey::generate();
        original.persist(&secret_path, &pubkey_path).unwrap();

        let loaded = NodeKey::load(&secret_path).unwrap();
        assert_eq!(original.secret.secret_bytes(), loaded.secret.secret_bytes());
        assert_eq!(original.pubkey.serialize(), loaded.pubkey.serialize());
        assert_eq!(original.node_id(), loaded.node_id());

        let pubkey_hex = std::fs::read_to_string(&pubkey_path).unwrap();
        assert_eq!(pubkey_hex.len(), 66, "compressed pubkey hex = 33 bytes × 2");

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn load_rejects_wrong_length_file() {
        let dir = std::env::temp_dir().join(format!("colorex-node-key-bad-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let path = dir.join("node.key");
        std::fs::write(&path, [0u8; 16]).unwrap();

        let err = NodeKey::load(&path).expect_err("16-byte file must reject");
        assert!(matches!(
            err,
            NodeKeyError::InvalidLength {
                expected: 32,
                actual: 16
            }
        ));

        let _ = std::fs::remove_dir_all(&dir);
    }
}
