[package]
name = "rfq-api"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
axum = { workspace = true, features = ["ws"] }
dotenvy = "0.15"
futures.workspace = true
http.workspace = true
rfq-btc = { path = "../../crates/rfq-btc", features = ["electrum"] }
rfq-consignment = { path = "../../crates/rfq-consignment" }
rfq-core = { path = "../../crates/rfq-core" }
rfq-maker = { path = "../../crates/rfq-maker" }
rfq-rgb = { path = "../../crates/rfq-rgb" }
rfq-router = { path = "../../crates/rfq-router" }
rfq-store = { path = "../../crates/rfq-store", features = ["postgres"] }
rfq-types = { path = "../../crates/rfq-types" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true
utoipa.workspace = true
utoipa-swagger-ui.workspace = true
uuid.workspace = true

[dev-dependencies]
serde_json.workspace = true
tower.workspace = true
