[package]
name = "rfq-router"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
async-trait.workspace = true
futures.workspace = true
reqwest.workspace = true
rfq-core = { path = "../rfq-core" }
rfq-types = { path = "../rfq-types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
